using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;

using UniRx;

[RequireComponent(typeof(ARPlaneManager), typeof(ARRaycastManager))]
public class PlaneVisualizerWithTouchLock : MonoBehaviour
{
    private ARPlaneManager planeManager;
    private ARRaycastManager raycastManager;

    private HashSet<ARPlane> initializedPlanes = new HashSet<ARPlane>();
    private Dictionary<ARPlane, Material> planeMaterials = new Dictionary<ARPlane, Material>();
    private static List<ARRaycastHit> hits = new List<ARRaycastHit>();

    public Font textFont;
    public float textScale = 0.03f;


    public Button[] btnOnOff;

    private bool planeLocked = false;


    public Text[] txtStatPlane;

    public event Action<bool> OnPlaneManagerEnabledChanged;
    private bool lastState;

    public MeshRenderer renderer;

    void Awake()
    {
        planeManager = GetComponent<ARPlaneManager>();
        raycastManager = GetComponent<ARRaycastManager>();

        lastState = planeManager.enabled;

        txtStatPlane[0].text = "1";
        txtStatPlane[1].text = "2";
        txtStatPlane[2].text = "3";
    }

    void Start()
    {
        AddButtonEvtListener();
    }

    void ApplyRandomColorRenderer(MeshRenderer renderer)
    {
        //var renderer = plane.GetComponent<MeshRenderer>();
        if (renderer != null)
        {
            Color randColor = new Color(UnityEngine.Random.value, UnityEngine.Random.value, UnityEngine.Random.value, 0.7f);
            Material newMat = new Material(renderer.material); // ë³µì‚¬í•´ì„œ ë”°ë¡œ ì‚¬ìš©
            newMat.color = randColor;
            renderer.material = newMat;
            //planeMaterials[plane] = newMat; // ì¶”í›„ ì¡°ì •ìš© ì €ì¥
        }
    }

    void AddButtonEvtListener()
    {
        foreach (Button btn in btnOnOff)
        {
            int index = Array.IndexOf(btnOnOff, btn);

            btn.onClick.AsObservable()
           .Subscribe(_ =>
           {
               //Debug.Log("Click");
               if (index == 0) TogglePlaneEnable();
               else if (index == 1) RemovePlanes();
           });
        }
    }

    private void TogglePlaneEnable()
    {
        planeManager.enabled = !planeManager.enabled;
    }

    private void RemovePlanes()
    {
        //planeManager.enabled = false;

        foreach (var plane in planeManager.trackables)
        {
            Destroy(plane.gameObject);
        }

        Debug.Log("ğŸ“´  Plane ì œê±° ì™„ë£Œ");
    }

    void OnEnable()
    {
        if (planeManager != null)
        {
            planeManager.planesChanged += OnPlanesChanged;

            this.OnPlaneManagerEnabledChanged += HandlePlaneDetectionToggle;
        }
    }

    void OnDisable()
    {
        if (planeManager != null)
        {
            planeManager.planesChanged -= OnPlanesChanged;
            this.OnPlaneManagerEnabledChanged -= HandlePlaneDetectionToggle;
        }
    }

    void HandlePlaneDetectionToggle(bool isEnabled)
    {
        Debug.Log($"ğŸ“¡ Plane ê°ì§€ ìƒíƒœ: {(isEnabled ? "í™œì„±í™”" : "ë¹„í™œì„±í™”")}");
        
        txtStatPlane[2].text = $"ğŸ“¡ Plane ê°ì§€ ìƒíƒœ: {(isEnabled ? "í™œì„±í™”" : "ë¹„í™œì„±í™”")}";
    }

    void Update()
    {
        if(Input.GetKeyDown(KeyCode.Alpha1))
        {
            //SceneManager.LoadScene("testEmptySingleton");
            //permission.PressBtnCapture();
             ApplyRandomColorRenderer(renderer);
        }

        //if (planeLocked) return;

        if (Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began)
        {
            Vector2 touchPos = Input.GetTouch(0).position;
            if (raycastManager.Raycast(touchPos, hits, TrackableType.Planes))
            {
                var planeHit = planeManager.GetPlane(hits[0].trackableId);
                if (planeHit != null)
                {
                    LockThisPlane(planeHit);
                }
            }
        }

        if (planeManager.enabled != lastState)
        {
            lastState = planeManager.enabled;
            Debug.Log($"[PlaneManager] ìƒíƒœ ë³€ê²½ë¨: {lastState}");

            txtStatPlane[2].text = $"[PlaneManager] enable ìƒíƒœ ë³€ê²½ë¨: {lastState}";

            OnPlaneManagerEnabledChanged?.Invoke(lastState);
        }
    }

    void OnPlanesChanged(ARPlanesChangedEventArgs args)
    {

        if (args.added.Count > 0)
        {

            foreach (var plane in args.added)
            {
                if (!initializedPlanes.Contains(plane))
                {
                    ApplyRandomColor(plane);
                    CreatePlaneLabel(plane);
                    initializedPlanes.Add(plane);

                }
            }
            
            foreach (ARPlane plane in args.added)
            {
                Debug.Log($"[Plane Detected] Plane Added: {plane.trackableId}");
                // ì—¬ê¸°ì— 'Planeì´ ì¤€ë¹„ë˜ì—ˆë‹¤'ëŠ” ë¡œì§ ì‚½ì…

                txtStatPlane[0].text = $"[Plane Detected] Plane Added: {plane.trackableId}";
            }

            // ì—…ë°ì´íŠ¸ëœ í‰ë©´
            foreach (ARPlane plane in args.updated)
            {
                Debug.Log($"[Plane Updated] {plane.trackableId}");
                txtStatPlane[1].text = $"[Plane Updated] Plane Updated: {plane.trackableId}";
            }

            // ì œê±°ëœ í‰ë©´
            foreach (ARPlane plane in args.removed)
            {
                //Debug.Log($"[Plane Removed] {plane.trackableId}");
                //txtStatPlane[2].text = $"[Plane Removed] Plane Removed: {plane.trackableId}";
            }
        }
    }

    void ApplyRandomColor(ARPlane plane)
    {
        var renderer = plane.GetComponent<MeshRenderer>();
        if (renderer != null)
        {
            Color randColor = new Color(UnityEngine.Random.value, UnityEngine.Random.value, UnityEngine.Random.value, 0.7f);
            Material newMat = new Material(renderer.material); // ë³µì‚¬í•´ì„œ ë”°ë¡œ ì‚¬ìš©
            newMat.color = randColor;
            renderer.material = newMat;
            //planeMaterials[plane] = newMat; // ì¶”í›„ ì¡°ì •ìš© ì €ì¥
        }
    }

    void CreatePlaneLabel(ARPlane plane)
    {
        GameObject textObj = new GameObject("PlaneID_Label");
        textObj.transform.SetParent(plane.transform);
        textObj.transform.localPosition = Vector3.zero;

        TextMesh textMesh = textObj.AddComponent<TextMesh>();
        textMesh.text = plane.trackableId.ToString().Substring(0, 8);
        textMesh.fontSize = 100;
        textMesh.characterSize = 0.05f;
        textMesh.anchor = TextAnchor.MiddleCenter;
        textMesh.alignment = TextAlignment.Center;
        textMesh.color = Color.black;

        if (textFont != null)
            textMesh.font = textFont;

        textObj.transform.localScale = Vector3.one * textScale;
    }

    void LockThisPlane(ARPlane selectedPlane)
    {
        Debug.Log($"ğŸ”’ Plane Locked: {selectedPlane.trackableId}");
        planeLocked = true;

        /*
        foreach (var plane in planeManager.trackables)
        {
            if (plane != selectedPlane)
            {
                plane.gameObject.SetActive(false);
            }
        }*/

        // ì•ŒíŒŒê°’ 0.9ë¡œ ê°•ì¡°
        if (planeMaterials.ContainsKey(selectedPlane))
        {
            var mat = planeMaterials[selectedPlane];
            Color c = mat.color;
            c.a = 0.9f;
            mat.color = c;
            selectedPlane.GetComponent<MeshRenderer>().material = mat;
        }

        // Plane ê°ì§€ ì¢…ë£Œ
        //planeManager.enabled = false;
    }
}

